### ISSUE TITLE
NullPointerException during update check

### ISSUE THREAD

**Issue by rocketman10404** [rocketman10404/tabbychat#5]
From masterX244:

"2013-06-19 14:08:58 [INFO] [STDERR] Exception in thread "Thread-33" java.lang.NullPointerException
2013-06-19 14:08:58 [INFO] [STDERR]     at acs.tabbychat.core.TabbyChat.addToChannel(TabbyChat.java:185)
2013-06-19 14:08:58 [INFO] [STDERR]     at acs.tabbychat.core.TabbyChat.printMessageToChat(TabbyChat.java:147)"

and

"2013-06-19 14:08:57 [INFO] [STDERR] java.lang.NullPointerException
2013-06-19 14:08:57 [INFO] [STDERR]     at acs.tabbychat.core.GuiNewChatTC.clearChatLines(GuiNewChatTC.java:95)
2013-06-19 14:08:57 [INFO] [STDERR]     at acs.tabbychat.core.TabbyChat.resetDisplayedChat(TabbyChat.java:633)
2013-06-19 14:08:57 [INFO] [STDERR]     at acs.tabbychat.core.TabbyChat.loadChannelData(TabbyChat.java:374)"

in same stacktrace

**Comment by rocketman10404** [comment]
The second NPE would seem to indicate that GuiNewChatTCs 'chatLines' field was null at the time of execution.  This field should be set by TabbyChatUtils.hookIntoChat method as a shallow copy of the vanilla class GuiNewChat's 'chatLines' field, which had already been performed by this point.  Thus, the only way this object could be null is if another mod overwrote GuiNewChat and left the 'chatLines' field unassigned. 

The first NPE occurred in a background thread, and would indicate that either a local ChatChannel object 'theChan' was unassigned (which is not possible here), or TabbyChat's 'channelMap' field had no value for the key "*", which is created when TabbyChat is loaded (via GuiNewChatTC's loading), which must've occurred for the background thread to be spawned.  

Therefore, it would seem that there are no possible conditions for this exception to be thrown without intervention by a third-party mod.

**Comment by rocketman10404** [comment]
User reports bug occurred in old version, have not experienced it so far on the latest.
